# Generated by Django 3.2.8 on 2021-10-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(blank='True', null=True, upload_to='social', verbose_name='Image'),
        ),
    ]
